### ISSUE TITLE
Remove references to apitest.dataverse.org (use demo server instead)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-client-java#2]
Per https://github.com/IQSS/dataverse/issues/3345 we plan to shut down the https://apitest.dataverse.org server so references to it should be removed.

https://demo.dataverse.org should used instead.

If there is any reason why the apitest is preferred to demo, please let me know.

**Comment by otter606** [comment]
This should be  fixed now, updated docs and defaults to new server.

**Comment by pdurbin** [comment]
Thanks!
