### ISSUE TITLE
testPostGetDeleteDataset failing due to unpublished dataverse passed in `-DdataverseAlias`

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-client-java#7]
Tested on 6d72b92 on Ubuntu 16.04. I ran the equivalent of `./gradlew clean test  -DdataverseServerURL=https://my.dataverse.org -DdataverseApiKey=xxx-xxx-xxx -DdataverseAlias=MY-DEMO-DATAVERSE` from the readme but one of the tests didn't pass:

![test_results_-_class_com researchspace dataverse http datasetoperationstest_-_2016-10-27_06 44 24](https://cloud.githubusercontent.com/assets/21006/19784117/833c08ba-9c62-11e6-97c9-71aec4c3c7ea.png)

Quite possibly I'm doing something wrong! I'm attaching the output I saw and a tarball of the build directory which contains the report in the screenshot above.
- [output.txt](https://github.com/IQSS/dataverse-client-java/files/556941/output.txt)
- [build.tar.gz](https://github.com/IQSS/dataverse-client-java/files/556940/build.tar.gz)

**Comment by richarda23** [comment]
Thanks for this. This is an integration test that makes a real call to a Dataverse account:

1. creates a new Dataset, D
2. uploads a file to D
3. publishes D as major version
4. changes the title of D
5. retrieves the versions

When I run this, there are 2 versions retrieved - the published one from step 3, and a draft version with a new title. 

Might it be that different accounts can be configured differently on how to handle publishing or versioning?  Alternatively it might be that setting the title has failed. I'll put in some additional logging statements in the test.

**Comment by pdurbin** [comment]
It looks like https://github.com/IQSS/dataverse-client-java/blob/6d72b92e631193dd24f51b1aca9757613754b749/src/test/java/com/researchspace/dataverse/http/DatasetOperationsTest.java#L55 is the test that is failing:

	@Test
	public void testPostGetDeleteDataset() throws IOException, InterruptedException, URISyntaxException {
		DatasetFacade facade = createFacade();
		Identifier id = dataverseOps.createDataset(facade, dataverseAlias);
		assertNotNull(id.getId());
		Dataset ds = datasetOps.getDataset(id);
		String doiId = ds.getDoiId().get();
		datasetOps.uploadFile(doiId, getTestFile());
		datasetOps.publishDataset (id, Version.MAJOR);
		
		facade.setTitle("Updated title2");
		datasetOps.updateDataset(facade, id);
		List<DatasetVersion> versions = datasetOps.getDatasetVersions(id);
		assertEquals(2, versions.size()); // published and draft <-- this is line 55
		assertEquals("RELEASED", versions.get(1).getVersionState());
		String msg = datasetOps.deleteDataset(id).getMessage();
		assertNotNull(msg);
		log.debug(msg);
	}

Does `MY-DEMO-DATAVERSE` at `-DdataverseAlias=MY-DEMO-DATAVERSE` need to be a published dataverse? There's a business rule in Dataverse that you can't publish a dataset until its parent dataverse has been published.

**Comment by richarda23** [comment]
Oh, that would be it then.
I'll amend the test not to make any assumptions on the publishing state of the Dataverse.
